name: Build App
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Baixar Gradle Wrapper
        run: |
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradle/wrapper/gradle-wrapper.jar

      - name: Dar Permissões
        run: |
          chmod +x gradlew
          ls -la

      - name: Gerar Arquivo .apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Baixar o App
        uses: actions/upload-artifact@v4
        with:
          name: GestaoDocumentosFrotas
          path: app/build/outputs/apk/debug/app-debug.apk
          
